var pi = 3.14;
var R ;
R = prompt("nhap đường kính :");
var bankinh;
bankinh = R/2;
console.log(bankinh);
var chuvi;
chuvi = R * pi;
console.log(chuvi);
var dientich;
dientich = bankinh * bankinh * pi;
console.log(dientich);
